apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::375025551341:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-F75NLKIC69TF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::375025551341:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-15T11:21:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1393"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a7abd3c2-7925-487c-99c5-374a27820be3
